language: r
# see also https://docs.travis-ci.com/user/languages/r

# see also https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  - osx

# Using the package cache to store R package dependencies can significantly
# speed up build times and is recommended for most builds.
cache:
  - apt
  - packages

# You will need to set sudo: false in order to use the container based builds
# and package caching.
sudo: false

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

latex: false
pandoc: false

r_binary_packages:
  - devtools
  - Rcpp

before_install:
    - wget -O spams.tar.gz http://spams-devel.gforge.inria.fr/hitcounter2.php?file=file/36615/spams-R-v2.6-2017-03-22.tar.gz
    - tar xvf spams.tar.gz
    - cd spams-R
    - R CMD INSTALL -l `pwd` spams-R/spams




